site_name: Inteligencia Artificial y Big Data
site_url: https://jmperez-profesor.github.io/iabd/

extra:
  homepage: https://jmperez-profesor.github.io/iabd/

theme:
  name: material
  language: es
  logo: images/logo.png
  favicon: images/favicon.png
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - toc.integrate
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    
  palette:
      - scheme: default
        primary: light green
        toggle:
          icon: material/toggle-switch-off-outline
          name: Cambiar a modo oscuro
      - scheme: slate
        primary: teal
        toggle:
          icon: material/toggle-switch
          name: Cambiar a modo normal
  plugins:
    - mkdocs-video:
        mark: "vid"
    - search:
      lang: es

      
markdown_extensions: 
  - admonition
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.caret   
  - pymdownx.critic 
  - pymdownx.details 
  - attr_list
  - md_in_html
  - footnotes

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true  # Opcional: crea enlaces de anclaje para las líneas
      line_spans: true       # Opcional: envuelve las líneas con <span> para mejor estilo
      pygments_lang_class: true
      linenums: true

nav:
  - Introducción: index.md 
  - Hugging Face:
    - hf/index.md
    - Gradio: hf/Ejemplo_gradio.md
    - Tasks: 
      - Visión por computador: hf/Tasks_vc.md
    #  - Textos: hf/Tasks_texts.md
    - Referencias: hf/Referencias.md
  - Datasets: 
    - Datasets/Datasets.md
    - Datasets/datasets_aitor.md
    - Actividades: 
      - Datasets/Actividad1.md
      #- Datasets/Actividad1_solution.md
    #- Entornos Windows: hf/Apuntes_Windows.md
    #- Ejercicios propuestos Windows: hf/Ejercicios_Windows.md
    
extra_css:
  - stylesheets/extra.css