site_name: Inteligencia Artificial y Big Data
site_url: https://jmperez-profesor.github.io/iabd/

extra:
  homepage: https://jmperez-profesor.github.io/iabd/

theme:
  name: material
  language: es
  logo: images/logo.png
  favicon: images/favicon.png
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - toc.integrate
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    
  palette:
      - scheme: default
        primary: light green
        toggle:
          icon: material/toggle-switch-off-outline
          name: Cambiar a modo oscuro
      - scheme: slate
        primary: teal
        toggle:
          icon: material/toggle-switch
          name: Cambiar a modo normal
  plugins:
    - mkdocs-video:
        mark: "vid"
    - search:
      lang: es

      
markdown_extensions: 
  - admonition
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.caret   
  - pymdownx.critic 
  - pymdownx.details 
  - attr_list
  - md_in_html
  - footnotes

nav:
  - Introducción: index.md 
  - Cloud: 
    - Sesión 1 Cloud y AWS: 
      - Reto Q Mejorado: cloud/sesion1/mejorada/retoq_mejorado.md
      - Reto Amazon Q: cloud/sesion1/actividad_ayuntamiento_elche.md
      - Reto Perplexity: cloud/sesion1/actividad_cloud_aws_perplexity.md
      - Reto copilot mejorado: cloud/sesion1/sesion1_cloud_aws_copilot_mejorado.md
      - Reto copilot: cloud/sesion1/sesion1_cloud_aws_copilot.md
      - Reto Gemini: cloud/sesion1/sesion1_cloud_aws_gemini.md
      - Reto Gemini+NoteBookLM: cloud/sesion1/sesion1_cloud_aws_proyecto_fenix.md
  - Bedrock: 
    - bedrock/sesion1.md
  - Hugging Face:
    - hf/index.md
    - Gradio: hf/Ejemplo_gradio.md
    - Tasks: 
      - Visión por computador: hf/Tasks_vc.md
      - Textos (NLP): 
        - Introducción: hf/nlp/01_intro.md
        - Reto1 - Sentimientos: hf/nlp/02_reto1_sentimientos.md
        - Solución Reto1 - Sentimientos: hf/nlp/soluciones/reto1_solucion.md
        - Reto2 - Clasificacion: hf/nlp/03_reto2_clasificacion.md
        - Solución Reto2 - Clasificacion: hf/nlp/soluciones/reto2_solucion.md
        - Reto3 - Generación: hf/nlp/04_reto3_generacion.md
        - Solución Reto3 - Generación: hf/nlp/soluciones/reto3_solucion.md
    - Referencias: hf/Referencias.md
  - Datasets: 
    - Datasets/Datasets.md
    - Datasets/datasets_aitor.md
    - Actividades: 
      - Datasets/Actividad1.md  
    
extra_css:
  - stylesheets/extra.css